openapi: "3.0.0"
info:
  version: 1.0.0
  title: DMU Gamja TEAM의 API docs
  description: 동양미래대학교 졸업 작품 GAMJA의 API 문서 입니다.
  license:
    name: MIT
servers:
  - url: http://localhost:3030/api
paths:
  /api/user:
    post:
      tags:
        - user
      summary: Create Local user
      description: 로컬 서비스 이용자 회원가입
      operationId: localUserCreate
      parameters:
        - email: email
          password: password
          name: name
          description: 이메일, 패스워드, 이름으로 회원가입
          required: true
          schema:
            type: string
      responses:
  /api/user/local:
    post:
      tags:
        - user
      summary: Login Local User
      description: 로컬 서비스 로그인
      operationId: localUserLogin
      parameters:
        - email: email
          password: password
          description: 이메일과 패스워드 로그인
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
            application/xml:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Invalid username supplied
        "404":
          description: User not found
  /api/user/kakao:
    get:
      tags:
        - user
      summary: Kakao Login
      description: "카카오 서비스 이용자 회원가입 및 로그인, a Tag로 해당 API 요청"
      operationId: KakaoLogin
      responses:
        "200":
          description: successful operation
          header:
            cookies:
              accessToken:
                description: 토큰 전달
  /api/gamja:
    get:
      tags:
        - gamja
      summary: Get Gamja Rank List
      description: 감자 랭킹 리스트 조회
      operationId: getGamjaList
      responses:
  /api/gamja/idx:
    get:
      tags:
        - gamja
      summary: Get MyGamja
      description: userIdx를 이용한 감자 조회
      operationId: getGamja
      responses:
  /api/gamja:
    post:
      tags:
        - gamja
      summary: Create Gamja
      description: 최초 감자 생성
      operationId: saveGamja
      parameters:
        - name: 감자 이름
          description: 감자 이름과 user Idx 이용한 감자 생성
          required: true
          schema:
            type: string
      responses:
  /api/gamja/exp/id:
    patch:
      tags:
        - gamja
      summary: Update Gamja Exp
      description: 감자 경험치 수정
      operationId: updateGamjaExp
      parameters:
        - exp: 수정 감자 경험치
          description: userIdx로 감자 조회 후 exp 수정
          required: true
          schema:
            type: string
      responses:
  /api/gamja/idx:
    patch:
      tags:
        - gamja
      summary: Update Gamja Name
      description: 감자 이름 수정
      operationId: updateGamjaName
      parameters:
        - name: 감자 이름
          description: userIdx로 감자 조회 후 name 수정
          required: true
          schema:
            type: string
      responses:
  /api/board:
    get:
      tags:
        - board
      summary: Board All Read
      description: 게시물 전체 조회
      operationId: BoardAllRead
      responses:
  /api/board/idx:
    get:
      tags:
        - board
      summary: Board Read
      description: 게시물 상세 조회
      operationId: BoardRead
      responses:
  /api/board/user/idx:
    get:
      tags:
        - board
      summary: Board User Read
      description: 유저의 게시물 조회
      operationId: UserBoardRead
      responses:
  /api/board:
    post:
      tags:
        - board
      summary: Save Board
      description: 게시글 생성
      operationId: SaveBoard
      parameters:
        - title: 게시글 제목
          text : 게시글 내용
          description: 게시글 내용, 제목
          required: true
          schema:
            type: string
      responses:
components:
  schemas:
    User:
      type: object
      properties:
        idx:
          type: integer
          format: int64
          example: 10
        email:
          type: string
          example: inhoo987654321@gmail.com
        password:
          type: string
          example: qwer1595@!
        name:
          type: string
          description: 유저의 이름
          example: 김인후
    Gamja:
      type: object
      properties:
        idx:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: 맥도날드감자튀김
        exp:
          type: integer
          example: 350
        userIdx:
          type: integer
          description: User의 PK값을 FK 사용
          example: 1
    Board:
      type: object
      properties:
        idx:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: 집 가고 싶다.
        text:
          type: string
          example: 오늘따라 매우 집 가고 싶다.
        userIdx:
          type: integer
          description: User의 PK값을 FK 사용
          example: 1
    Recode:
      type: object
      properties:
        idx:
          type: integer
          format: int64
          example: 10
        menu:
          type: string
          example: 당근
        kcal:
          type: double
          example: 30.5
        userIdx:
          type: integer
          description: User의 PK값을 FK 사용
          example: 1
    UserInfo:
      type: object
      properties:
        idx:
          type: integer
          format: int64
          example: 10
        birth:
          type: DATETIME
          example: 2022-12-13
        gender:
          type: boolean
          description: true 남자, false 여자
          example: false
        userIdx:
          type: integer
          description: User의 PK값을 FK 사용
          example: 1
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: "##default"
